/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HexIt;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author udit gupta
 */
public class Hex_editor extends javax.swing.JFrame {

    /**
     * Creates new form Hex_editor
     */
    public Hex_editor() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ConvertText = new javax.swing.JTextField();
        From = new javax.swing.JComboBox<>();
        Swap = new javax.swing.JButton();
        To = new javax.swing.JComboBox<>();
        Convertbtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        InputFeild = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        OutputFeild = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        MainHexSpace = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        first = new javax.swing.JTextField();
        seconf = new javax.swing.JTextField();
        Third = new javax.swing.JTextField();
        fourth = new javax.swing.JTextField();
        seconf1 = new javax.swing.JTextField();
        seconf2 = new javax.swing.JTextField();
        seconf3 = new javax.swing.JTextField();
        seconf4 = new javax.swing.JTextField();
        seconf5 = new javax.swing.JTextField();
        seconf6 = new javax.swing.JTextField();
        seconf7 = new javax.swing.JTextField();
        seconf8 = new javax.swing.JTextField();
        seconf9 = new javax.swing.JTextField();
        seconf10 = new javax.swing.JTextField();
        seconf11 = new javax.swing.JTextField();
        seconf12 = new javax.swing.JTextField();
        seconf13 = new javax.swing.JTextField();
        seconf14 = new javax.swing.JTextField();
        seconf15 = new javax.swing.JTextField();
        seconf16 = new javax.swing.JTextField();
        seconf17 = new javax.swing.JTextField();
        seconf18 = new javax.swing.JTextField();
        seconf19 = new javax.swing.JTextField();
        seconf20 = new javax.swing.JTextField();
        seconf21 = new javax.swing.JTextField();
        seconf22 = new javax.swing.JTextField();
        seconf23 = new javax.swing.JTextField();
        seconf24 = new javax.swing.JTextField();
        seconf25 = new javax.swing.JTextField();
        seconf26 = new javax.swing.JTextField();
        seconf27 = new javax.swing.JTextField();
        seconf28 = new javax.swing.JTextField();
        seconf29 = new javax.swing.JTextField();
        seconf30 = new javax.swing.JTextField();
        seconf31 = new javax.swing.JTextField();
        seconf32 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        TopMenuBar = new javax.swing.JMenuBar();
        FileOption = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        EditOption = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hex It");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        ConvertText.setEditable(false);
        ConvertText.setBackground(new java.awt.Color(0, 0, 0));
        ConvertText.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        ConvertText.setForeground(new java.awt.Color(255, 0, 0));
        ConvertText.setText("Hex Converter");
        ConvertText.setBorder(null);
        ConvertText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertTextActionPerformed(evt);
            }
        });

        From.setBackground(new java.awt.Color(153, 255, 153));
        From.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        From.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hexadecimal", "Decimal", "ASCII" }));
        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });

        Swap.setBackground(new java.awt.Color(255, 255, 102));
        Swap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Swap.setForeground(new java.awt.Color(255, 255, 51));
        Swap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/smallsort.png"))); // NOI18N
        Swap.setBorder(null);
        Swap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SwapMouseClicked(evt);
            }
        });
        Swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwapActionPerformed(evt);
            }
        });

        To.setBackground(new java.awt.Color(153, 255, 153));
        To.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hexadecimal", "Decimal", "ASCII" }));

        Convertbtn.setBackground(new java.awt.Color(255, 255, 102));
        Convertbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Convertbtn.setText("Convert");
        Convertbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConvertbtnMouseClicked(evt);
            }
        });

        InputFeild.setBackground(new java.awt.Color(255, 255, 204));
        InputFeild.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane4.setViewportView(InputFeild);

        OutputFeild.setEditable(false);
        OutputFeild.setBackground(new java.awt.Color(255, 255, 204));
        OutputFeild.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane7.setViewportView(OutputFeild);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ConvertText, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Swap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Convertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ConvertText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(To, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(From, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Swap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Convertbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        MainHexSpace.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setAutoscrolls(true);

        first.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        first.setText("DD");
        first.setMinimumSize(new java.awt.Dimension(15, 15));
        first.setPreferredSize(new java.awt.Dimension(15, 15));

        seconf.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf.setText("DD");
        seconf.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf.setPreferredSize(new java.awt.Dimension(20, 15));

        Third.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Third.setText("DD");
        Third.setMinimumSize(new java.awt.Dimension(20, 15));
        Third.setPreferredSize(new java.awt.Dimension(20, 15));
        Third.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThirdActionPerformed(evt);
            }
        });

        fourth.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        fourth.setText("DD");
        fourth.setMinimumSize(new java.awt.Dimension(20, 15));
        fourth.setPreferredSize(new java.awt.Dimension(20, 15));
        fourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthActionPerformed(evt);
            }
        });

        seconf1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf1.setText("DD");
        seconf1.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf1.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf2.setText("DD");
        seconf2.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf2.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf3.setText("DD");
        seconf3.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf3.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf4.setText("DD");
        seconf4.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf4.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf5.setText("DD");
        seconf5.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf5.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf6.setText("DD");
        seconf6.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf6.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf7.setText("DD");
        seconf7.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf7.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf8.setText("DD");
        seconf8.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf8.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf9.setText("DD");
        seconf9.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf9.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf10.setText("DD");
        seconf10.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf10.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf11.setText("DD");
        seconf11.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf11.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf12.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf12.setText("DD");
        seconf12.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf12.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf13.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf13.setText("DD");
        seconf13.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf13.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf14.setText("DD");
        seconf14.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf14.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf15.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf15.setText("DD");
        seconf15.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf15.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf16.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf16.setText("DD");
        seconf16.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf16.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf17.setText("DD");
        seconf17.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf17.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf18.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf18.setText("DD");
        seconf18.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf18.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf19.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf19.setText("DD");
        seconf19.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf19.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf20.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf20.setText("DD");
        seconf20.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf20.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf21.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf21.setText("DD");
        seconf21.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf21.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf22.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf22.setText("DD");
        seconf22.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf22.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf23.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf23.setText("DD");
        seconf23.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf23.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf24.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf24.setText("DD");
        seconf24.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf24.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf25.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf25.setText("DD");
        seconf25.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf25.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf26.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf26.setText("DD");
        seconf26.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf26.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf27.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf27.setText("DD");
        seconf27.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf27.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf28.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf28.setText("DD");
        seconf28.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf28.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf29.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf29.setText("DD");
        seconf29.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf29.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf30.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf30.setText("DD");
        seconf30.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf30.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf31.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf31.setText("DD");
        seconf31.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf31.setPreferredSize(new java.awt.Dimension(20, 15));

        seconf32.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        seconf32.setText("DD");
        seconf32.setMinimumSize(new java.awt.Dimension(20, 15));
        seconf32.setPreferredSize(new java.awt.Dimension(20, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seconf32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Third, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(seconf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seconf15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seconf15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Third, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seconf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seconf16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seconf31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seconf32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainHexSpace.addTab("tab2", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainHexSpace)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(MainHexSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        jTextField1.setText("Hex Calculator");
        jTextField1.setBorder(null);

        jTextPane1.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane6.setViewportView(jTextPane1);

        jTextPane2.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(jTextPane2);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 255, 0));
        jTextField2.setText("Opreation -");
        jTextField2.setBorder(null);

        jTextPane3.setEditable(false);
        jTextPane3.setBackground(new java.awt.Color(255, 255, 204));
        jTextPane3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jTextPane3);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Calculate");

        jTextField3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 255, 0));
        jTextField3.setText("Result : ");
        jTextField3.setBorder(null);

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 255, 0));
        jTextField4.setText("Input 1");
        jTextField4.setBorder(null);

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 255, 0));
        jTextField5.setText("Input 2");
        jTextField5.setBorder(null);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(153, 255, 153));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Subtact", "Mutiply", "Divide", "Xor", "RightShift", "LeftShift" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TopMenuBar.setBackground(new java.awt.Color(204, 255, 255));
        TopMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TopMenuBar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TopMenuBar.setName(""); // NOI18N

        FileOption.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Open File");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FileOption.add(jMenuItem1);

        TopMenuBar.add(FileOption);

        EditOption.setText("Edit");
        TopMenuBar.add(EditOption);

        setJMenuBar(TopMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConvertTextActionPerformed

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromActionPerformed

    private void SwapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SwapMouseClicked
        // TODO add your handling code here:
        int temp;
        temp = From.getSelectedIndex();
        From.setSelectedIndex(To.getSelectedIndex());
        To.setSelectedIndex(temp);
    }//GEN-LAST:event_SwapMouseClicked
        // Main Function
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.out.println("File is opening");
        try{  
        //constructor of file class having file as argument  
            JFileChooser j = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            int r = j.showOpenDialog(null); 
            if (r == JFileChooser.APPROVE_OPTION){ 
                // set the label to the path of the selected file 
                String Path =  j.getSelectedFile().getAbsolutePath();
                System.out.println(Path);
                StringTokenizer Tokens = new StringTokenizer(Path, "\\"); 
                String File_Name = null;
                while (Tokens.hasMoreTokens()) 
                    File_Name = Tokens.nextToken();
                System.out.println(File_Name);
                if(this.TabCount == 0){
                    //this.MainHexSpace.removeAll();
                    this.TabCount += 1;
                }
                FileTabs Tab = new FileTabs();
                Tab.setContent(Path);
                this.MainHexSpace.addTab(File_Name, Tab.getPanel());
                this.MainHexSpace.setSelectedComponent(Tab.getPanel());
                //MainHexSpace.addTab('', jMenu1);
                //Output.setText(Content);
            } 
            else
                System.out.println("the user cancelled the operation"); 
        }  catch(Exception e) {  
            e.printStackTrace();  
        }    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void SwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwapActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
        // Converter
    private void ConvertbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvertbtnMouseClicked
        // TODO add your handling code here:
        String from = this.From.getItemAt(From.getSelectedIndex());
        String to = this.To.getItemAt(To.getSelectedIndex());
        String input = this.InputFeild.getText();
        if(input!=""){
            if(from=="Hexadecimal"&&to=="Decimal"){
                if(validInput("Hex-Dec", input)){
                    String output = "helllo";
                    this.OutputFeild.setText(output);
                }
                else{
                    this.OutputFeild.setText("==========    Invalid Input    ==========");
                }
            }
            else if(from=="Hexadecimal"&&to=="ASCII"){
                if(validInput("Hex-Str", input)){
                    byte[] castedinput = input.getBytes();
                    String output = hexToString(castedinput);
                    this.OutputFeild.setText(output);
                }
                else{
                    this.OutputFeild.setText("==========    Invalid Input    ==========");
                }
            }
        }
        else{
            this.OutputFeild.setText("==========    Invalid Input    ==========");
        }
    }//GEN-LAST:event_ConvertbtnMouseClicked

    private void fourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourthActionPerformed

    private void ThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThirdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThirdActionPerformed
    private String hexToString(byte[] output) {
        char hexDigit[] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                                    'A', 'B', 'C', 'D', 'E', 'F' };
        StringBuffer buf = new StringBuffer();
        for (int j = 0; j < output.length; j++) {
            buf.append(hexDigit[(output[j] >> 4) & 0x0f]);
            buf.append(hexDigit[output[j] & 0x0f]);
        }
        return buf.toString();

    }
    private boolean validInput(String type, String Text){
        if( type=="Hex-Dec" ){
            if ( Text.matches("-?[0-9a-fA-F]+") ){
                return true;
            }
            return false;
        }
        else if( type=="Hex-Str" ){
            return true;
        }
        return false;
    }
    private int TabCount = 0;
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConvertText;
    private javax.swing.JButton Convertbtn;
    private javax.swing.JMenu EditOption;
    private javax.swing.JMenu FileOption;
    private javax.swing.JComboBox<String> From;
    private javax.swing.JTextPane InputFeild;
    private javax.swing.JTabbedPane MainHexSpace;
    private javax.swing.JTextPane OutputFeild;
    private javax.swing.JButton Swap;
    private javax.swing.JTextField Third;
    private javax.swing.JComboBox<String> To;
    private javax.swing.JMenuBar TopMenuBar;
    private javax.swing.JTextField first;
    private javax.swing.JTextField fourth;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField seconf;
    private javax.swing.JTextField seconf1;
    private javax.swing.JTextField seconf10;
    private javax.swing.JTextField seconf11;
    private javax.swing.JTextField seconf12;
    private javax.swing.JTextField seconf13;
    private javax.swing.JTextField seconf14;
    private javax.swing.JTextField seconf15;
    private javax.swing.JTextField seconf16;
    private javax.swing.JTextField seconf17;
    private javax.swing.JTextField seconf18;
    private javax.swing.JTextField seconf19;
    private javax.swing.JTextField seconf2;
    private javax.swing.JTextField seconf20;
    private javax.swing.JTextField seconf21;
    private javax.swing.JTextField seconf22;
    private javax.swing.JTextField seconf23;
    private javax.swing.JTextField seconf24;
    private javax.swing.JTextField seconf25;
    private javax.swing.JTextField seconf26;
    private javax.swing.JTextField seconf27;
    private javax.swing.JTextField seconf28;
    private javax.swing.JTextField seconf29;
    private javax.swing.JTextField seconf3;
    private javax.swing.JTextField seconf30;
    private javax.swing.JTextField seconf31;
    private javax.swing.JTextField seconf32;
    private javax.swing.JTextField seconf4;
    private javax.swing.JTextField seconf5;
    private javax.swing.JTextField seconf6;
    private javax.swing.JTextField seconf7;
    private javax.swing.JTextField seconf8;
    private javax.swing.JTextField seconf9;
    // End of variables declaration//GEN-END:variables
}
